language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

before_install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls

script:
  - go vet ./...
  - go test -v -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci

-after_success:
  - coveralls
  